### PR TITLE
[PR] Bring results made from refactoring

### PR DESCRIPTION
**Pull request by DveloperY0115**
### Major Changes
- **Overall project structure.** Now sources and libraries are organized in a way being more 'python-ic'
- _Frequently used classes and functions_, such as the class **FrameCapture** and functions like _process_frame_, _process_default_, and _any wrappers of opencv-python_ are now organized under a single class named **FrameProcessor** to prevent memory overhead and improve usability
- Every sources related to YOLOv4, YOLOv5 are now **REMOVED** from the project. I will explain it later in this report
- Instead, our computer vision functionality of autopilot system will be developed based on YOLOv3 algorithm and I already cloned a repository as a git submodule under 'library' directory (Check this out!)

### Reason Why I Brought These Changes
First, in the context that we are dealing with python language, **I think it's more preferable to keep our codes and files simple.** Instead of dividing the codes into many different folders, put them all together in a single directory, namely **core** will make our project to be more flexible and less error-prone.

Second, yes, **I screwed up making changes in pre-existing YOLO repositories and I think I should come up with better ideas and designs** to use it in more encapsulated ways. So, as I mentioned above, I removed previously used YOLO projects from this project and decided to restart from scratch.

Third, capturing frames and processing it are important in this project. But I think they can be put in a single file which will be enlarged as we need & add more utilities for doing miscellaneous (yet important) tasks in our project. So to keep it clean, I put them into a single file called _utils.py_ under _core_.

### Required Future Discussions
1. The tasks we were working on maybe one month ago was to make a script for collecting and organizing data generated during gameplay, but I think we should all discuss about it since lots of time passed from then.

2. I managed to add external git repository 'yolov3-tf2' via git submodule, but I couldn't do it for our lane detection library, for consistency, we should first remove files from the project and then add it again using 'git submodule'.

### CODE REVIEW

**Review by juyoungml — APPROVED** [review]
LGTM. I will delete the files according to lane detection as soon as possible. Thanks for your work!

**Comment by DveloperY0115** [comment]
> LGTM. I will delete the files according to lane detection as soon as possible. Thanks for your work!

Ah, in fact, probably you won't have to. After creating this pull request, I've done additional work for refactoring. 

And this work includes the refactoring of external libraries that will be frequently used throughout this project. I've done commits on this but I haven't yet pushed it. Thus, I'll open review session for you ASAP.

**Comment by Danielle-Jeong** [comment]
LGBT. Thank you for your contribution on this project!

**Review by tejava317 — COMMENTED** [review]
LGTM. Thank you for your contribution on this project!

**Review by tejava317 — APPROVED** [review]
LGTM

**Review by hbg1345 — APPROVED** [review]

**Pull request merged**
